In [15]:
%load_ext autoreload

In [20]:
%autoreload 2

In [1]:
from src.parsers import mimic, hirid
from src.modeling import discovery, plots, querier
from src.utils import constants

In [2]:
import sys
# import win32com.client
import os
import pandas as pd

def setup_io_config(root_path):
    """
    Input - Output config. Add dataset paths
    :root_path -> Repo path which contains 'data' and 'res' folders
    """

    # MIMIC
    is_shortcut = True if "data.lnk" in os.listdir(root_path) else False 
    
    if (is_shortcut):
        path_shortcut =  os.path.join(root_path, "data.lnk")
        shell = win32com.client.Dispatch("WScript.Shell")
        mimic_data = shell.CreateShortCut(path_shortcut).Targetpath
    else:
        mimic_data = os.path.join(f"{root_path}", "data") 
    mimic_path = os.path.join(f"{root_path}", "results")

    # HIRID
    hirid_data = f'{root_path}/data/hirid-a-high-time-resolution-icu-dataset-1.1.1/raw_stage/'
    hirid_path = f'{root_path}/data/hirid-a-high-time-resolution-icu-dataset-1.1.1'
    
    return mimic_data, mimic_path, hirid_data, hirid_path

def setup_stratification_config():
    gender="MF"
    age_b=40
    age_a=80 
    ethnicity="WHITE" 
    lab_mapping= constants.LAB_MAPPING
    b_w = [(0,6), (6,12)]
    a_w = [(0,4), (4,8), (8,12)]
    before_windows = b_w
    after_windows = a_w
    return gender, age_a, age_b, ethnicity, lab_mapping, before_windows, after_windows

In [3]:
# IO Config
# root_path ="C:\\Users\\danco\\My Drive\\Master\\Datasets\\MIMIC iii"
root_path = "/Users/pavan/Library/CloudStorage/GoogleDrive-f20190038@hyderabad.bits-pilani.ac.in/My Drive/TAU/Code/DrugLab"
data, res, raw_path, res_path = setup_io_config(root_path=root_path)

# Stratification Config
gender, age_a, age_b, ethnicity, lab_mapping, before_windows, after_windows = setup_stratification_config()

In [ ]:
# MIMIC
mimic_parser = mimic.MIMICParser(data=data, res=res, gender=gender, age_b=age_b, age_a=age_a, ethnicity=ethnicity, load="AUTOMATIC_MAPPING_MIMIC")
m_med1, m_med2, m_labs = mimic_parser.parse(use_pairs=False, load_from_raw=False, load_raw_chartevents=False)

## Querier
mimic_data_querier = querier.DatasetQuerier(
    data = data,
    res = res,
    t_labs=m_labs, 
    t_med1=m_med1, 
    t_med2=m_med2,
    gender=gender, 
    age_b=age_b, 
    age_a=age_a, 
    ethnicity=ethnicity, 
    lab_mapping=lab_mapping
)
# query pairs for all medication and lab tests
m_final_lab_med_data = mimic_data_querier.generate_med_lab_data(before_windows, after_windows)
# Querying pairs for a single medication and lab test
b_w = [(0,6), (6,12)]
a_w = [(0,4), (4,8), (8,12)]
med_lab_pair_1 = mimic_data_querier.query('Insulin - Regular', 'Glucose', b_w, a_w)

## Discovery Analysis for the queried medication and lab test pairs in the chosen before and after windows
analyzer = discovery.ClinicalDiscoveryAnalysis(m_final_lab_med_data)
pvals_med_lab = analyzer.analyze(before_windows, after_windows)
sig_med_lab = analyzer.generate_significant(pvals_med_lab.dropna(subset=["TTest Paired"]))

## Plots
plotter = plots.ClinicalPlotAnalysis(
    data = data,
    res = res,
    gender=gender, 
    age_b=age_b, 
    age_a=age_a, 
    ethnicity=ethnicity, 
    lab_mapping=lab_mapping
)
m_corrs_data_df = plotter.plot(m_final_lab_med_data, m_labs, before_windows=before_windows, after_windows=after_windows)

In [5]:
# HIRID
hirid_mapping = constants.HIRID_MAPPING
lab_parts = (30,45)
hirid_parser = hirid.HiRiDParser(data=raw_path, res=res_path, gender=gender, age_b=age_b, age_a=age_a, load="MANUAL_MAPPING_HIRID")
h_med1, h_med2, h_labs = hirid_parser.parse(lab_parts=lab_parts)
hirid_data_querier = querier.DatasetQuerier(
    data = raw_path,
    res = res_path,
    t_labs=h_labs, 
    t_med1=h_med1, 
    t_med2=h_med2,
    gender=gender, 
    age_b=age_b, 
    age_a=age_a, 
    ethnicity=ethnicity, 
)
final_h_final_lab_med_data, raw_h_final_lab_med_data = hirid_data_querier.generate_med_lab_data(before_windows, after_windows, lab_parts=lab_parts)

/Users/pavan/Desktop/TAU/DrugLab/src/parsers/hirid.py:85: DtypeWarning: Columns (4) have mixed types. Specify dtype option on import or set low_memory=False.
  labs = pd.read_csv(path)
/Users/pavan/Desktop/TAU/DrugLab/src/parsers/hirid.py:85: DtypeWarning: Columns (4) have mixed types. Specify dtype option on import or set low_memory=False.
  labs = pd.read_csv(path)
/Users/pavan/Desktop/TAU/DrugLab/src/parsers/hirid.py:85: DtypeWarning: Columns (4,5) have mixed types. Specify dtype option on import or set low_memory=False.
  labs = pd.read_csv(path)
/Users/pavan/Desktop/TAU/DrugLab/src/parsers/hirid.py:85: DtypeWarning: Columns (4) have mixed types. Specify dtype option on import or set low_memory=False.
  labs = pd.read_csv(path)
/Users/pavan/Desktop/TAU/DrugLab/src/parsers/hirid.py:85: DtypeWarning: Columns (4) have mixed types. Specify dtype option on import or set low_memory=False.
  labs = pd.read_csv(path)
/Users/pavan/Desktop/TAU/DrugLab/src/parsers/hirid.py:85: DtypeWarning: Columns (4) have mixed types. Specify dtype option on import or set low_memory=False.
  labs = pd.read_csv(path)
/Users/pavan/Desktop/TAU/DrugLab/src/parsers/hirid.py:85: DtypeWarning: Columns (4) have mixed types. Specify dtype option on import or set low_memory=False.
  labs = pd.read_csv(path)
/Users/pavan/Desktop/TAU/DrugLab/src/parsers/hirid.py:85: DtypeWarning: Columns (4) have mixed types. Specify dtype option on import or set low_memory=False.
  labs = pd.read_csv(path)
/Users/pavan/Desktop/TAU/DrugLab/src/parsers/hirid.py:85: DtypeWarning: Columns (4) have mixed types. Specify dtype option on import or set low_memory=False.
  labs = pd.read_csv(path)
/Users/pavan/Desktop/TAU/DrugLab/src/parsers/hirid.py:85: DtypeWarning: Columns (4) have mixed types. Specify dtype option on import or set low_memory=False.
  labs = pd.read_csv(path)
/Users/pavan/Desktop/TAU/DrugLab/src/parsers/hirid.py:85: DtypeWarning: Columns (4) have mixed types. Specify dtype option on import or set low_memory=False.
  labs = pd.read_csv(path)
/Users/pavan/Desktop/TAU/DrugLab/src/parsers/hirid.py:85: DtypeWarning: Columns (4) have mixed types. Specify dtype option on import or set low_memory=False.
  labs = pd.read_csv(path)
/Users/pavan/Desktop/TAU/DrugLab/src/parsers/hirid.py:85: DtypeWarning: Columns (4) have mixed types. Specify dtype option on import or set low_memory=False.
  labs = pd.read_csv(path)
/Users/pavan/Desktop/TAU/DrugLab/src/parsers/hirid.py:85: DtypeWarning: Columns (4) have mixed types. Specify dtype option on import or set low_memory=False.
  labs = pd.read_csv(path)
/Users/pavan/Desktop/TAU/DrugLab/src/parsers/hirid.py:85: DtypeWarning: Columns (4) have mixed types. Specify dtype option on import or set low_memory=False.
  labs = pd.read_csv(path)

In [ ]:
final_h_final_lab_med_data

,HADM_ID,OldITEMID,STARTTIME,ENDTIME,givendose,cumulativedose,fluidamount_calc,cumulfluidamount_calc,doseunit,route,...,"after_time_(4, 8)_sp","after_trends_(4, 8)_sp","after_abs_(4, 8)_sp","after_mean_(4, 8)_sp","after_std_(8, 12)_sp","after_time_(8, 12)_sp","after_trends_(8, 12)_sp","after_abs_(8, 12)_sp","after_mean_(8, 12)_sp",LAB_NAME
0,14,15,2127-12-09 08:36:00,2127-12-09 08:36:05.703,0.0,0.0,0.0,0.0,U,iv-inf,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Alanine aminotransferase [Enzymatic activity/v...
1,14,15,2127-12-09 08:36:00,2127-12-09 08:36:05.703,0.0,0.0,0.0,0.0,U,iv-inf,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Aspartate aminotransferase [Enzymatic activity...
2,14,15,2127-12-09 08:36:00,2127-12-09 08:36:05.703,0.0,0.0,0.0,0.0,U,iv-inf,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Bilirubin.total [Moles/volume] in Serum or Plasma
3,14,15,2127-12-09 08:36:00,2127-12-09 08:36:05.703,0.0,0.0,0.0,0.0,U,iv-inf,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Core body temperature
4,14,15,2127-12-09 08:36:00,2127-12-09 08:36:05.703,0.0,0.0,0.0,0.0,U,iv-inf,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Creatinine [Moles/volume] in Blood
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
230602,33792,1000436,2119-08-02 19:14:00,2119-08-02 19:14:53.113,2.5,2.5,2.5,2.5,mg,iv-inj,...,NaN,NaN,NaN,NaN,NaN,10.751913,NaN,73.00,73.00,Creatinine [Moles/volume] in Blood
230603,33792,1000436,2119-08-02 19:14:00,2119-08-02 19:14:53.113,2.5,2.5,2.5,2.5,mg,iv-inj,...,NaN,NaN,NaN,NaN,NaN,10.751913,NaN,103.00,103.00,Hemoglobin [Mass/volume] in Blood
230604,33792,1000436,2119-08-02 19:14:00,2119-08-02 19:14:53.113,2.5,2.5,2.5,2.5,mg,iv-inj,...,NaN,NaN,NaN,NaN,NaN,10.751913,NaN,1.37,1.37,Magnesium [Moles/volume] in Blood
230605,33792,1000436,2119-08-02 19:14:00,2119-08-02 19:14:53.113,2.5,2.5,2.5,2.5,mg,iv-inj,...,NaN,NaN,NaN,NaN,NaN,10.751913,NaN,0.90,0.90,Methemoglobin/Hemoglobin.total in Arterial blood
230606,33792,1000436,2119-08-02 19:14:00,2119-08-02 19:14:53.113,2.5,2.5,2.5,2.5,mg,iv-inj,...,NaN,NaN,NaN,NaN,NaN,10.751913,NaN,137.00,137.00,Sodium [Moles/volume] in Blood

In [7]:
# final_h_final_lab_med_data = pd.read_csv(os.path.join(res_path, f"before_after_windows_main_med_lab_trends_first_val_40-80_MF_WHITE_doc_eval_win_{lab_parts}.csv")).drop(columns=["Unnamed: 0"])

In [ ]:
# final_h_final_lab_med_data - 20,30

,HADM_ID,OldITEMID,STARTTIME,ENDTIME,givendose,cumulativedose,fluidamount_calc,cumulfluidamount_calc,doseunit,route,...,"after_time_(4, 8)_sp","after_trends_(4, 8)_sp","after_abs_(4, 8)_sp","after_mean_(4, 8)_sp","after_std_(8, 12)_sp","after_time_(8, 12)_sp","after_trends_(8, 12)_sp","after_abs_(8, 12)_sp","after_mean_(8, 12)_sp",LAB_NAME
0,14,15,2127-12-09 08:36:00,2127-12-09 08:36:05.703,0.0,0.0,0.0,0.0,U,iv-inf,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Alanine aminotransferase [Enzymatic activity/v...
1,14,15,2127-12-09 08:36:00,2127-12-09 08:36:05.703,0.0,0.0,0.0,0.0,U,iv-inf,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Aspartate aminotransferase [Enzymatic activity...
2,14,15,2127-12-09 08:36:00,2127-12-09 08:36:05.703,0.0,0.0,0.0,0.0,U,iv-inf,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Bilirubin.total [Moles/volume] in Serum or Plasma
3,14,15,2127-12-09 08:36:00,2127-12-09 08:36:05.703,0.0,0.0,0.0,0.0,U,iv-inf,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Core body temperature
4,14,15,2127-12-09 08:36:00,2127-12-09 08:36:05.703,0.0,0.0,0.0,0.0,U,iv-inf,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Creatinine [Moles/volume] in Blood
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
230602,33792,1000436,2119-08-02 19:14:00,2119-08-02 19:14:53.113,2.5,2.5,2.5,2.5,mg,iv-inj,...,NaN,NaN,NaN,NaN,NaN,10.751913,NaN,73.00,73.00,Creatinine [Moles/volume] in Blood
230603,33792,1000436,2119-08-02 19:14:00,2119-08-02 19:14:53.113,2.5,2.5,2.5,2.5,mg,iv-inj,...,NaN,NaN,NaN,NaN,NaN,10.751913,NaN,103.00,103.00,Hemoglobin [Mass/volume] in Blood
230604,33792,1000436,2119-08-02 19:14:00,2119-08-02 19:14:53.113,2.5,2.5,2.5,2.5,mg,iv-inj,...,NaN,NaN,NaN,NaN,NaN,10.751913,NaN,1.37,1.37,Magnesium [Moles/volume] in Blood
230605,33792,1000436,2119-08-02 19:14:00,2119-08-02 19:14:53.113,2.5,2.5,2.5,2.5,mg,iv-inj,...,NaN,NaN,NaN,NaN,NaN,10.751913,NaN,0.90,0.90,Methemoglobin/Hemoglobin.total in Arterial blood
230606,33792,1000436,2119-08-02 19:14:00,2119-08-02 19:14:53.113,2.5,2.5,2.5,2.5,mg,iv-inj,...,NaN,NaN,NaN,NaN,NaN,10.751913,NaN,137.00,137.00,Sodium [Moles/volume] in Blood

In [ ]:
# HIRID
hirid_mapping = constants.HIRID_MAPPING
lab_parts = (45,60)
hirid_parser = hirid.HiRiDParser(data=raw_path, res=res_path, gender=gender, age_b=age_b, age_a=age_a, load="MANUAL_MAPPING_HIRID")
h_med1, h_med2, h_labs = hirid_parser.parse(lab_parts=lab_parts)
hirid_data_querier = querier.DatasetQuerier(
    data = raw_path,
    res = res_path,
    t_labs=h_labs, 
    t_med1=h_med1, 
    t_med2=h_med2,
    gender=gender, 
    age_b=age_b, 
    age_a=age_a, 
    ethnicity=ethnicity, 
)
final_h_final_lab_med_data, raw_h_final_lab_med_data = hirid_data_querier.generate_med_lab_data(before_windows, after_windows, lab_parts=lab_parts)

In [ ]:
final_h_final_lab_med_data

,HADM_ID,OldITEMID,STARTTIME,ENDTIME,givendose,cumulativedose,fluidamount_calc,cumulfluidamount_calc,doseunit,route,...,"after_time_(4, 8)_sp","after_trends_(4, 8)_sp","after_abs_(4, 8)_sp","after_mean_(4, 8)_sp","after_std_(8, 12)_sp","after_time_(8, 12)_sp","after_trends_(8, 12)_sp","after_abs_(8, 12)_sp","after_mean_(8, 12)_sp",LAB_NAME
0,14,15,2127-12-09 08:36:00,2127-12-09 08:36:05.703,0.0,0.0,0.0,0.0,U,iv-inf,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Alanine aminotransferase [Enzymatic activity/v...
1,14,15,2127-12-09 08:36:00,2127-12-09 08:36:05.703,0.0,0.0,0.0,0.0,U,iv-inf,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Aspartate aminotransferase [Enzymatic activity...
2,14,15,2127-12-09 08:36:00,2127-12-09 08:36:05.703,0.0,0.0,0.0,0.0,U,iv-inf,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Bilirubin.total [Moles/volume] in Serum or Plasma
3,14,15,2127-12-09 08:36:00,2127-12-09 08:36:05.703,0.0,0.0,0.0,0.0,U,iv-inf,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Core body temperature
4,14,15,2127-12-09 08:36:00,2127-12-09 08:36:05.703,0.0,0.0,0.0,0.0,U,iv-inf,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Creatinine [Moles/volume] in Blood
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
230602,33792,1000436,2119-08-02 19:14:00,2119-08-02 19:14:53.113,2.5,2.5,2.5,2.5,mg,iv-inj,...,NaN,NaN,NaN,NaN,NaN,10.751913,NaN,73.00,73.00,Creatinine [Moles/volume] in Blood
230603,33792,1000436,2119-08-02 19:14:00,2119-08-02 19:14:53.113,2.5,2.5,2.5,2.5,mg,iv-inj,...,NaN,NaN,NaN,NaN,NaN,10.751913,NaN,103.00,103.00,Hemoglobin [Mass/volume] in Blood
230604,33792,1000436,2119-08-02 19:14:00,2119-08-02 19:14:53.113,2.5,2.5,2.5,2.5,mg,iv-inj,...,NaN,NaN,NaN,NaN,NaN,10.751913,NaN,1.37,1.37,Magnesium [Moles/volume] in Blood
230605,33792,1000436,2119-08-02 19:14:00,2119-08-02 19:14:53.113,2.5,2.5,2.5,2.5,mg,iv-inj,...,NaN,NaN,NaN,NaN,NaN,10.751913,NaN,0.90,0.90,Methemoglobin/Hemoglobin.total in Arterial blood
230606,33792,1000436,2119-08-02 19:14:00,2119-08-02 19:14:53.113,2.5,2.5,2.5,2.5,mg,iv-inj,...,NaN,NaN,NaN,NaN,NaN,10.751913,NaN,137.00,137.00,Sodium [Moles/volume] in Blood

In [10]:
## Discovery Analysis for the queried medication and lab test pairs in the chosen before and after windows
analyzer = discovery.ClinicalDiscoveryAnalysis(final_h_final_lab_med_data)
types_l = ["abs", "mean", "std", "trends"]
pvals_med_lab = analyzer.analyze(before_windows, after_windows, min_patients=100, types_l=types_l)

pval, hard, bonferroni, fdr = analyzer.generate_significant(pvals_med_lab.dropna(subset=["TTest Paired"]))
fdr.to_csv(f"temp_hirid_sig_med_lab_pairs_fdr_{lab_parts}.csv")
bonferroni.to_csv(f"temp_hirid_sig_med_lab_pairs_bonferroni_{lab_parts}.csv")
hard.to_csv(f"temp_hirid_sig_med_lab_pairs_hard_{lab_parts}.csv")
pval.to_csv(f"temp_hirid_sig_med_lab_pairs_pval_{lab_parts}.csv")

### Part (20,30)

In [11]:
fdr

,Lab Name,Med Name,Before Window (in Hours),After Window (in Hours),Mannwhitneyu Test,TTest Independent,TTest Paired,No of Patients,Type,BonferroniPvals,FDR Benjamini Corrected
1,Glucose [Moles/volume] in Serum or Plasma,Aspirin Tbl 100 mg,"(6, 12)","(0, 4)",3.925488e-03,1.498655e-03,4.136229e-04,170,abs,9.380966e-01,2.931552e-03
4,Glucose [Moles/volume] in Serum or Plasma,Aspirin Tbl 100 mg,"(6, 12)","(0, 4)",3.925488e-03,1.498655e-03,4.136229e-04,170,abs,9.380966e-01,2.931552e-03
7,Glucose [Moles/volume] in Serum or Plasma,Aspirin Tbl 100 mg,"(6, 12)","(0, 4)",3.925488e-03,1.498655e-03,4.136229e-04,170,abs,9.380966e-01,2.931552e-03
10,Glucose [Moles/volume] in Serum or Plasma,Aspirin Tbl 100 mg,"(6, 12)","(0, 4)",3.925488e-03,1.498655e-03,4.136229e-04,170,abs,9.380966e-01,2.931552e-03
37,Metronidazole tabl 200 mg,Aspirin Tbl 100 mg,"(6, 12)","(0, 4)",2.707403e-04,4.712771e-03,5.573528e-04,318,abs,1.000000e+00,3.762131e-03
...,...,...,...,...,...,...,...,...,...,...,...
2263,Sodium [Moles/volume] in Blood,Zinacef Amp 1.5 g,"(6, 12)","(4, 8)",1.422564e-11,1.734177e-10,1.247550e-22,122,abs,2.829444e-19,1.768403e-20
2264,Sodium [Moles/volume] in Blood,Zinacef Amp 1.5 g,"(0, 6)","(0, 4)",2.084845e-03,1.494074e-02,6.539287e-11,215,abs,1.483110e-07,1.951461e-09
2265,Sodium [Moles/volume] in Blood,Zinacef Amp 1.5 g,"(6, 12)","(0, 4)",4.529972e-15,2.136277e-12,8.201370e-38,183,abs,1.860071e-34,4.650177e-35
2266,Sodium [Moles/volume] in Blood,Zinacef Amp 1.5 g,"(0, 6)","(4, 8)",3.279583e-04,1.964945e-03,2.701681e-10,161,abs,6.127413e-07,6.962969e-09
2267,Sodium [Moles/volume] in Blood,Zinacef Amp 1.5 g,"(6, 12)","(4, 8)",1.422564e-11,1.734177e-10,1.247550e-22,122,abs,2.829444e-19,1.768403e-20

In [12]:
bonferroni

,Lab Name,Med Name,Before Window (in Hours),After Window (in Hours),Mannwhitneyu Test,TTest Independent,TTest Paired,No of Patients,Type,BonferroniPvals,FDR Benjamini Corrected
112,Sodium [Moles/volume] in Blood,Aspirin Tbl 100 mg,"(0, 6)","(0, 4)",6.553098e-02,1.263894e-01,9.460759e-08,103,abs,2.145700e-04,1.625530e-06
113,Sodium [Moles/volume] in Blood,Aspirin Tbl 100 mg,"(0, 6)","(0, 4)",6.553098e-02,1.263894e-01,9.460759e-08,103,abs,2.145700e-04,1.625530e-06
114,Sodium [Moles/volume] in Blood,Aspirin Tbl 100 mg,"(0, 6)","(0, 4)",6.553098e-02,1.263894e-01,9.460759e-08,103,abs,2.145700e-04,1.625530e-06
115,Sodium [Moles/volume] in Blood,Aspirin Tbl 100 mg,"(0, 6)","(0, 4)",6.553098e-02,1.263894e-01,9.460759e-08,103,abs,2.145700e-04,1.625530e-06
218,Heart rate,Beloc ZOK ret Tbl 25 mg,"(0, 6)","(4, 8)",6.322243e-03,9.620576e-03,3.519466e-07,146,abs,7.982148e-04,5.251413e-06
...,...,...,...,...,...,...,...,...,...,...,...
2263,Sodium [Moles/volume] in Blood,Zinacef Amp 1.5 g,"(6, 12)","(4, 8)",1.422564e-11,1.734177e-10,1.247550e-22,122,abs,2.829444e-19,1.768403e-20
2264,Sodium [Moles/volume] in Blood,Zinacef Amp 1.5 g,"(0, 6)","(0, 4)",2.084845e-03,1.494074e-02,6.539287e-11,215,abs,1.483110e-07,1.951461e-09
2265,Sodium [Moles/volume] in Blood,Zinacef Amp 1.5 g,"(6, 12)","(0, 4)",4.529972e-15,2.136277e-12,8.201370e-38,183,abs,1.860071e-34,4.650177e-35
2266,Sodium [Moles/volume] in Blood,Zinacef Amp 1.5 g,"(0, 6)","(4, 8)",3.279583e-04,1.964945e-03,2.701681e-10,161,abs,6.127413e-07,6.962969e-09
2267,Sodium [Moles/volume] in Blood,Zinacef Amp 1.5 g,"(6, 12)","(4, 8)",1.422564e-11,1.734177e-10,1.247550e-22,122,abs,2.829444e-19,1.768403e-20

### Part (10,20)

In [ ]:
fdr

,Lab Name,Med Name,Before Window (in Hours),After Window (in Hours),Mannwhitneyu Test,TTest Independent,TTest Paired,No of Patients,Type,BonferroniPvals,FDR Benjamini Corrected
28,Calcium.ionized [Moles/volume] in Blood,Benuron supp 1000 mg,"(0, 6)","(0, 4)",1.153321e-06,0.000005,1.902946e-15,157,abs,3.824921e-13,2.490544e-13
30,Glucose [Moles/volume] in Serum or Plasma,Benuron supp 1000 mg,"(0, 6)","(0, 4)",1.026727e-04,0.000394,8.537959e-08,191,abs,1.716130e-05,4.195735e-06
36,Potassium [Moles/volume] in Blood,Benuron supp 1000 mg,"(0, 6)","(0, 4)",2.431379e-03,0.001420,1.043715e-07,159,abs,2.097868e-05,4.195735e-06
37,Respiratory rate,Benuron supp 1000 mg,"(0, 6)","(0, 4)",1.101796e-08,0.003749,7.012093e-06,270,abs,1.409431e-03,1.566034e-04
38,Sodium [Moles/volume] in Blood,Benuron supp 1000 mg,"(0, 6)","(0, 4)",9.826408e-06,0.000122,2.478154e-15,157,abs,4.981089e-13,2.490544e-13
39,Calcium.ionized [Moles/volume] in Blood,Dafalgan Brausetbl 1g,"(6, 12)","(0, 4)",1.642939e-02,0.021772,8.501055e-06,121,abs,1.708712e-03,1.708712e-04
74,Metronidazole tabl 200 mg,Dormicum inj 1 mg/ml,"(0, 6)","(0, 4)",2.309590e-03,0.003959,1.909392e-06,229,abs,3.837877e-04,4.818827e-05
77,Heart rate,Ebrantil Inj Lsg,"(0, 6)","(0, 4)",2.919198e-01,0.323706,4.668884e-04,190,abs,9.384457e-02,7.218813e-03
91,Metronidazole tabl 200 mg,Fentanyl inj 50 µg/ml,"(0, 6)","(0, 4)",4.586420e-02,0.048784,2.076345e-04,729,abs,4.173453e-02,3.477878e-03
189,Respiratory rate,Tracrium inj 10 mg/ml,"(0, 6)","(0, 4)",3.797414e-06,0.002019,6.965143e-05,149,abs,1.399994e-02,1.272722e-03
190,Calcium.ionized [Moles/volume] in Blood,Zinacef Amp 1.5 g,"(0, 6)","(0, 4)",7.292428e-03,0.042667,1.151588e-06,186,abs,2.314691e-04,3.857819e-05
198,Potassium [Moles/volume] in Blood,Zinacef Amp 1.5 g,"(0, 6)","(0, 4)",1.551256e-03,0.001693,1.917941e-06,190,abs,3.855062e-04,4.818827e-05
200,Sodium [Moles/volume] in Blood,Zinacef Amp 1.5 g,"(0, 6)","(0, 4)",2.183177e-03,0.009609,5.021684e-10,189,abs,1.009359e-07,3.364528e-08

In [7]:
bonferroni

,Lab Name,Med Name,Before Window (in Hours),After Window (in Hours),Mannwhitneyu Test,TTest Independent,TTest Paired,No of Patients,Type,BonferroniPvals,FDR Benjamini Corrected
28,Calcium.ionized [Moles/volume] in Blood,Benuron supp 1000 mg,"(0, 6)","(0, 4)",1.153321e-06,0.000005,1.902946e-15,157,abs,3.824921e-13,2.490544e-13
30,Glucose [Moles/volume] in Serum or Plasma,Benuron supp 1000 mg,"(0, 6)","(0, 4)",1.026727e-04,0.000394,8.537959e-08,191,abs,1.716130e-05,4.195735e-06
36,Potassium [Moles/volume] in Blood,Benuron supp 1000 mg,"(0, 6)","(0, 4)",2.431379e-03,0.001420,1.043715e-07,159,abs,2.097868e-05,4.195735e-06
37,Respiratory rate,Benuron supp 1000 mg,"(0, 6)","(0, 4)",1.101796e-08,0.003749,7.012093e-06,270,abs,1.409431e-03,1.566034e-04
38,Sodium [Moles/volume] in Blood,Benuron supp 1000 mg,"(0, 6)","(0, 4)",9.826408e-06,0.000122,2.478154e-15,157,abs,4.981089e-13,2.490544e-13
39,Calcium.ionized [Moles/volume] in Blood,Dafalgan Brausetbl 1g,"(6, 12)","(0, 4)",1.642939e-02,0.021772,8.501055e-06,121,abs,1.708712e-03,1.708712e-04
74,Metronidazole tabl 200 mg,Dormicum inj 1 mg/ml,"(0, 6)","(0, 4)",2.309590e-03,0.003959,1.909392e-06,229,abs,3.837877e-04,4.818827e-05
190,Calcium.ionized [Moles/volume] in Blood,Zinacef Amp 1.5 g,"(0, 6)","(0, 4)",7.292428e-03,0.042667,1.151588e-06,186,abs,2.314691e-04,3.857819e-05
198,Potassium [Moles/volume] in Blood,Zinacef Amp 1.5 g,"(0, 6)","(0, 4)",1.551256e-03,0.001693,1.917941e-06,190,abs,3.855062e-04,4.818827e-05
200,Sodium [Moles/volume] in Blood,Zinacef Amp 1.5 g,"(0, 6)","(0, 4)",2.183177e-03,0.009609,5.021684e-10,189,abs,1.009359e-07,3.364528e-08

In [ ]:

h_plotter = plots.ClinicalPlotAnalysis(
    data = raw_path,
    res = res_path,
    gender=gender, 
    age_b=age_b, 
    age_a=age_a, 
    ethnicity="", 
    lab_mapping={}
)
h_corrs_data_df = h_plotter.plot(final_h_final_lab_med_data, h_labs, before_windows=before_windows, after_windows=after_windows)